version: '3.8'
services:
  med-adn:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        NEXT_PUBLIC_API_URL: https://med-adn.com/api/v1
        NEXT_PUBLIC_APP_URL: https://med-adn.com
        NEXT_PUBLIC_APP_NAME: med-adn
    container_name: med-adn-production
    expose:
      - 3000
    networks:
      - dokploy-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.med-adn-router.rule=Host(`med-adn.com`)"
        - "traefik.http.routers.med-adn-router.entrypoints=websecure"
        - "traefik.http.routers.med-adn-router.tls=true"
        - "traefik.http.routers.med-adn-router.tls.certresolver=letsencrypt"
        - "traefik.http.services.med-adn-service.loadbalancer.server.port=3000"
        - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true