version: '3.8'

services:
  med-adn:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        NEXT_PUBLIC_API_URL: https://med-adn.com/api/v1
        NEXT_PUBLIC_APP_URL: https://med-adn.com
        NEXT_PUBLIC_APP_NAME: med-adn
    container_name: med-adn-production
    expose:
      - 3000
    environment:
      - NODE_ENV=production
    networks:
      - dokploy-network
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # Match this exactly to your domain
        - "traefik.http.routers.med-adn.rule=Host(`med-adn.com`) || Host(`www.med-adn.com`)"
        - "traefik.http.routers.med-adn.entrypoints=websecure"
        - "traefik.http.routers.med-adn.tls=true"
        - "traefik.http.routers.med-adn.tls.certresolver=letsencrypt"
        - "traefik.http.services.med-adn.loadbalancer.server.port=3000"
        - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true