"use client";

import React, { useEffect, useMemo, useState, useRef } from "react";
import { AnimatePresence, motion, MotionConfig } from "motion/react";
import useMeasure from "react-use-measure";
// Card components removed - component is now wrapped by parent Card
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/animate-ui/components/radix/switch";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { Slider } from "@/components/ui/slider";
import {
  UnitSelectSheet,
  ModuleSelectSheet,
  CourseSelectSheet,
  SimpleMultiSelectDialog,
  MultiSelectDialog,
  MultiSelectSheet,
} from "@/components/student/practice/dialog-selectors";
import { ChevronLeft, ChevronRight, CheckCircle2, X, CheckSquare, Square, RefreshCw } from "lucide-react";
import { cn } from "@/lib/utils";
import { useUserSubscriptions, selectEffectiveActiveSubscription } from "@/hooks/use-subscription";

import { useQuizFilters } from "@/hooks/use-quiz-api";
import { useDebounce } from "@/hooks/use-debounce";
import { useContentFilters, useQuizSessionFilters, useQuestionCount } from "@/hooks/use-content-filters";
import { useYearLevel } from "@/hooks/use-year-level";

import { YearLevelSelector } from "@/components/student/shared/year-level-selector";

export type PracticeSessionPayload = {
  title: string;
  program?: string;
  unitId?: number;
  moduleId?: number;
  courseIds?: number[];
  availableCount?: number; // UI-computed available to clamp before sending
  filters: {
    types?: string[]; // e.g., ['qcm','qcs']
    quizSourceIds?: number[];
    // New: explicit selection of quiz years (e.g., 2020, 2021, 2024)
    quizYears?: number[];
  };
  questionCount?: number;
  timeLimit?: number; // in minutes
};

export function SessionWizard({
  onCancel,
  onCreate,
  isCreating = false,
}: {
  onCancel: () => void;
  onCreate: (payload: PracticeSessionPayload) => void;
  isCreating?: boolean;
}) {
  const [step, setStep] = useState(1);
  const [direction, setDirection] = useState<number>(1);
  const [contentRef, bounds] = useMeasure();

  // Load user's active subscription and fetch content filters
  const { subscriptions, loading: subsLoading } = useUserSubscriptions();
  const { filters: quizFilters } = useQuizFilters();

  // Detect year level from subscription
  // Only apply filtering for SEVEN (Résidanat) students
  const {
    yearLevel: detectedYearLevel,
    effectiveYearLevel,
    shouldApplyFilter,
    loading: yearLevelLoading
  } = useYearLevel();

  const [selectedYearLevel, setSelectedYearLevel] = useState<string | null>(null);

  // Use selected year level if set, otherwise use effective year level (only SEVEN)
  const activeYearLevel = selectedYearLevel || effectiveYearLevel;

  const { filters: contentFilters, loading: contentLoading, error: contentError } = useContentFilters({
    yearLevel: activeYearLevel
  });
  const { filters: sessionFilters, loading: sessionFiltersLoading, error: sessionFiltersError, refetch: refetchSessionFilters } = useQuizSessionFilters();
  const { questionCount: availableQuestionCount, totalQuestionCount, loading: questionCountLoading, error: questionCountError, refetch: refetchQuestionCount } = useQuestionCount();

  // University selection logic removed - hardcoded to universityId 1


  // Step 1
  const [title, setTitle] = useState("");
  const [unitId, setUnitId] = useState<string>("");
  const [moduleIds, setModuleIds] = useState<string[]>([]);
  const [courseIds, setCourseIds] = useState<string[]>([]);

  // Step 2 filters
  const [types, setTypes] = useState<string[]>([]);
  const [quizYears, setQuizYears] = useState<number[]>([]);
  const [quizSourceIds, setQuizSourceIds] = useState<number[]>([]);
  // Rotations removed from practice creation - always send empty array
  const [questionCount, setQuestionCount] = useState<number>(0);
  const [repetitionOnly, setRepetitionOnly] = useState<boolean>(false);

  // Step 2 filters
  const [program, setProgram] = useState<string>("");
  const [timeLimit, setTimeLimit] = useState<number | undefined>(undefined);

  const progressPct = useMemo(() => (step / 2) * 100, [step]);

  const next = () => {
    if (step < 2) {
      setDirection(1);
      setStep((s) => s + 1);
    }
  };
  const prev = () => {
    if (step > 1) {
      setDirection(-1);
      setStep((s) => s - 1);
    }
  };

  const clearAllSelections = () => {
    setUnitId("");
    setModuleIds([]);
    setCourseIds([]);
    setTypes([]);
    setQuizYears([]);
    setQuizSourceIds([]);
    setQuestionCount(0);
    setTimeLimit(undefined);
    setRepetitionOnly(false);
    // Title will be auto-generated by useEffect when courseIds changes
  };

  // Handle course selection without limits
  const handleCourseSelection = (selectedCourseIds: string[]) => {
    setCourseIds(selectedCourseIds);
  };

  // Build options from content filters
  const unitOptions = useMemo(() => {
    console.log('🔍 [Practice Session Wizard] Content Filters Data:', contentFilters);
    console.log('🔍 [Practice Session Wizard] Unites from backend:', contentFilters?.unites);
    console.log('🔍 [Practice Session Wizard] Independent Modules from backend:', contentFilters?.independentModules);

    const units = contentFilters?.unites?.map((u: any) => ({ value: String(u.id), label: u.name })) || [];
    console.log('🔍 [Practice Session Wizard] Processed Unit Options:', units);

    return units;
  }, [contentFilters]);

  const moduleOptions = useMemo(() => {
    const modules: any[] = [];

    console.log('🔍 [Practice Session Wizard] Building module options...');

    // Add modules from unites
    (contentFilters?.unites || []).forEach((u: any, uniteIndex: number) => {
      console.log(`🔍 [Practice Session Wizard] Processing Unite ${uniteIndex + 1}:`, u);
      console.log(`🔍 [Practice Session Wizard] Unite ${u.name} has ${u.modules?.length || 0} modules:`, u.modules);

      (u.modules || []).forEach((m: any, moduleIndex: number) => {
        console.log(`🔍 [Practice Session Wizard] Adding module ${moduleIndex + 1} from unite ${u.name}:`, m);
        modules.push({
          value: String(m.id),
          label: m.name,
          unitId: String(u.id),
          unitName: u.name,
          description: m.description
        });
      });
    });

    // Add independent modules
    (contentFilters?.independentModules || []).forEach((m: any, moduleIndex: number) => {
      console.log(`🔍 [Practice Session Wizard] Adding independent module ${moduleIndex + 1}:`, m);
      modules.push({
        value: String(m.id),
        label: `${m.name} (Independent)`,
        unitId: null,
        unitName: null,
        description: m.description,
        isIndependent: true
      });
    });

    console.log('🔍 [Practice Session Wizard] Final Module Options:', modules);
    console.log('🔍 [Practice Session Wizard] Total modules found:', modules.length);

    return modules;
  }, [contentFilters]);

  // Extract courses from content filters based on selected modules or unit
  const courseOptions = useMemo(() => {
    if (!contentFilters) return [];

    const courses: any[] = [];

    console.log('🔍 [Practice Session Wizard] Extracting courses from content filters...');

    // If a unit is selected, get all courses from that unit's modules
    if (unitId && unitId !== "") {
      const selectedUnit = contentFilters.unites?.find((u: any) => String(u.id) === unitId);
      if (selectedUnit) {
        console.log(`🔍 [Practice Session Wizard] Found selected unit: ${selectedUnit.name}`);
        (selectedUnit.modules || []).forEach((module: any) => {
          console.log(`🔍 [Practice Session Wizard] Processing module: ${module.name} with ${module.courses?.length || 0} courses`);
          (module.courses || []).forEach((course: any) => {
            courses.push({
              value: String(course.id),
              label: course.name,
              description: course.description,
              moduleId: String(module.id),
              unitId: unitId,
              questionCount: 0 // Will be updated via question count API
            });
          });
        });
      }
    }
    // If specific modules are selected, get courses from those modules
    else if (moduleIds.length > 0) {
      console.log(`🔍 [Practice Session Wizard] Processing ${moduleIds.length} selected modules`);

      // Check modules within units
      (contentFilters.unites || []).forEach((unit: any) => {
        (unit.modules || []).forEach((module: any) => {
          if (moduleIds.includes(String(module.id))) {
            console.log(`🔍 [Practice Session Wizard] Found selected module in unit: ${module.name}`);
            (module.courses || []).forEach((course: any) => {
              courses.push({
                value: String(course.id),
                label: course.name,
                description: course.description,
                moduleId: String(module.id),
                unitId: String(unit.id),
                questionCount: 0 // Will be updated via question count API
              });
            });
          }
        });
      });

      // Check independent modules
      (contentFilters.independentModules || []).forEach((module: any) => {
        if (moduleIds.includes(String(module.id))) {
          console.log(`🔍 [Practice Session Wizard] Found selected independent module: ${module.name}`);
          (module.courses || []).forEach((course: any) => {
            courses.push({
              value: String(course.id),
              label: course.name,
              description: course.description,
              moduleId: String(module.id),
              unitId: null, // Independent modules don't belong to a unit
              questionCount: 0 // Will be updated via question count API
            });
          });
        }
      });
    }

    console.log(`🔍 [Practice Session Wizard] Total courses extracted: ${courses.length}`);
    return courses;
  }, [contentFilters, unitId, moduleIds]);

  // Auto-generate title based on course selection with randomness
  const generateAlphabeticTitle = (): string => {
    const adjectives = [
      "Advanced", "Basic", "Clinical", "Diagnostic", "Essential", "Focused", "General", "Intensive",
      "Medical", "Practical", "Quick", "Review", "Specialized", "Targeted", "Comprehensive", "Interactive"
    ];
    const sessionTypes = [
      "Practice", "Session", "Study", "Review", "Training", "Preparation", "Assessment", "Evaluation",
      "Exercise", "Quiz", "Test", "Challenge", "Workout", "Drill"
    ];

    // Get course names for title generation
    const selectedCourseNames = courseIds
      .map(courseId => {
        const course = courseOptions.find((c: any) => c.value === courseId);
        const courseName = course?.label?.split(' (')[0]; // Remove any parenthetical info
        // Sanitize course name to contain only alphanumeric characters and spaces
        return courseName?.replace(/[^A-Za-z0-9\s]/g, '').trim();
      })
      .filter(Boolean)
      .slice(0, 2); // Limit to first 2 courses for readability

    // Add randomness with timestamp to ensure uniqueness
    const randomSeed = Date.now() + Math.random();
    const randomAdjective = adjectives[Math.floor(randomSeed * adjectives.length) % adjectives.length];
    const randomSessionType = sessionTypes[Math.floor(randomSeed * sessionTypes.length) % sessionTypes.length];

    // Build title based on selections
    if (selectedCourseNames.length > 0) {
      // Use "and" instead of "&" to keep only alphabets and numbers
      const coursesPart = selectedCourseNames.join(" and ");
      // Add random number for uniqueness when same courses selected
      const randomNum = Math.floor(Math.random() * 100) + 1;
      return `${coursesPart} ${randomSessionType} ${randomNum}`;
    }

    // Fallback to adjective + session type with random number
    const randomNum = Math.floor(Math.random() * 100) + 1;
    return `${randomAdjective} ${randomSessionType} ${randomNum}`;
  };

  // Auto-generate title when wizard starts
  useEffect(() => {
    if (!title) {
      const autoTitle = generateAlphabeticTitle();
      setTitle(autoTitle);
    }
  }, []);

  // Regenerate title when courses change
  useEffect(() => {
    const autoTitle = generateAlphabeticTitle();
    setTitle(autoTitle);
  }, [courseIds]);

  // Filter options by current selections
  const availableUnits = unitOptions;
  const availableModules = useMemo(() => {
    // When a unit is selected, show only modules from that unit
    if (unitId && unitId !== "") {
      return moduleOptions.filter((m: any) => m.unitId === unitId);
    }
    // When no unit is selected, show only independent modules
    else {
      return moduleOptions.filter((m: any) => m.isIndependent === true);
    }
  }, [moduleOptions, unitId]);

  const availableCourses = useMemo(() => {
    // If we're loading content filters or have an error, return empty array
    if (contentLoading || contentError || !courseOptions.length) {
      return [];
    }

    // If a unit is selected AND specific modules are also selected,
    // filter courses by those modules only
    if (unitId && unitId !== "" && moduleIds.length > 0) {
      const selectedModules = new Set(moduleIds);
      return courseOptions.filter((c: any) =>
        c.moduleId && selectedModules.has(c.moduleId)
      );
    }

    // If only a unit is selected (no modules), show all courses from that unit
    if (unitId && unitId !== "") {
      return courseOptions;
    }

    // If modules are selected (without a unit), filter courses by those modules
    if (moduleIds.length > 0) {
      const selectedModules = new Set(moduleIds);
      return courseOptions.filter((c: any) =>
        !c.moduleId || selectedModules.has(c.moduleId)
      );
    }

    // No selection, no courses available
    return [];
  }, [courseOptions, unitId, moduleIds, contentLoading, contentError]);

  // Handle removing individual courses
  const removeCourse = (courseIdToRemove: string) => {
    setCourseIds(prev => prev.filter(id => id !== courseIdToRemove));
  };

  // Handle selecting/deselecting all courses
  const selectAllCourses = () => {
    const allCourseIds = availableCourses.map((c: any) => c.value);
    setCourseIds(allCourseIds);
  };

  const deselectAllCourses = () => {
    setCourseIds([]);
  };

  const areAllCoursesSelected = availableCourses.length > 0 && courseIds.length === availableCourses.length;

  // Helper function to extract course IDs from content filters based on selections
  const extractCourseIdsFromContentFilters = (): number[] => {
    if (!contentFilters) return [];

    const courseIds: number[] = [];

    // If a unit is selected, collect all course IDs from that unit's modules
    if (unitId && unitId !== "") {
      const selectedUnit = contentFilters.unites?.find((u: any) => u.id === Number(unitId));
      if (selectedUnit?.modules) {
        selectedUnit.modules.forEach((module: any) => {
          if (module.courses) {
            module.courses.forEach((course: any) => {
              courseIds.push(course.id);
            });
          }
        });
      }
    }
    // If specific modules are selected, collect course IDs from those modules
    else if (moduleIds.length > 0) {
      const selectedModuleIds = moduleIds.map(Number);

      // Check modules within unites
      contentFilters.unites?.forEach((unite: any) => {
        unite.modules?.forEach((module: any) => {
          if (selectedModuleIds.includes(module.id) && module.courses) {
            module.courses.forEach((course: any) => {
              courseIds.push(course.id);
            });
          }
        });
      });

      // Check independent modules
      contentFilters.independentModules?.forEach((module: any) => {
        if (selectedModuleIds.includes(module.id) && module.courses) {
          module.courses.forEach((course: any) => {
            courseIds.push(course.id);
          });
        }
      });
    }
    // If specific courses are selected, use those
    else if (courseIds.length > 0) {
      return courseIds.map(Number);
    }

    return [...new Set(courseIds)]; // Remove duplicates
  };

  // Handle selecting/deselecting all modules
  const selectAllModules = () => {
    const allModuleIds = availableModules.map((m: any) => m.value);
    setModuleIds(allModuleIds);
    setCourseIds([]); // Clear courses when modules change
  };

  const deselectAllModules = () => {
    setModuleIds([]);
    setCourseIds([]); // Clear courses when modules change
  };

  const areAllModulesSelected = availableModules.length > 0 && moduleIds.length === availableModules.length;

  // Handle selecting/deselecting all exam years
  const availableYearOptions = (sessionFilters?.examYears || []);
  const selectAllYears = () => {
    setQuizYears([...availableYearOptions]);
  };

  const deselectAllYears = () => {
    setQuizYears([]);
  };

  const areAllYearsSelected = availableYearOptions.length > 0 && quizYears.length === availableYearOptions.length;

  // Handle selecting/deselecting all sources
  const availableSourceOptions = (sessionFilters?.questionSources || []);
  const selectAllSources = () => {
    const allSourceIds = availableSourceOptions.map((s: any) => Number(s.id));
    setQuizSourceIds(allSourceIds);
  };

  const deselectAllSources = () => {
    setQuizSourceIds([]);
  };

  const areAllSourcesSelected = availableSourceOptions.length > 0 && quizSourceIds.length === availableSourceOptions.length;



  // Rotations removed from practice creation

  // Handle selecting/deselecting all question types
  const availableTypeOptions = [{ label: 'QCM', value: 'qcm' }, { label: 'QCS', value: 'qcs' }, { label: 'QROC', value: 'qroc' }];
  const selectAllTypes = () => {
    setTypes(['qcm', 'qcs', 'qroc']);
  };

  const deselectAllTypes = () => {
    setTypes([]);
  };

  const areAllTypesSelected = types.length === availableTypeOptions.length;

  // Title suggestion from API/context (fallback): build from selections when empty
  const suggestedTitle = useMemo(() => {
    if (title.trim()) return title;
    const unitName = availableUnits.find((u: any) => u.value === unitId)?.label;
    const firstModule = availableModules.find((m: any) => moduleIds.includes(m.value));
    const moduleName = firstModule?.label;
    const courseLabels = courseOptions.filter((c: any) => courseIds.includes(c.value)).map((c: any) => c.label.split(' (')[0]);
    const base = courseLabels.slice(0, 2).join(', ') || moduleName || unitName || 'Practice Serie';
    return base;
  }, [title, unitId, moduleIds, courseIds, availableUnits, availableModules, courseOptions]);

  // Compute allowed yearLevels from subscriptions
  const allowedYearLevels = useMemo(() => {
    return selectEffectiveActiveSubscription(subscriptions).allowedYearLevels;
  }, [subscriptions]);

  // Real-time counts via API with 300ms debounce using new endpoint
  const selectedCourseIdsNum = useMemo(() => {
    // If specific courses are selected, use those
    if (courseIds.length > 0) {
      return courseIds.map(Number);
    }
    // Otherwise, extract course IDs from unit/module selections
    return extractCourseIdsFromContentFilters();
  }, [courseIds, unitId, moduleIds, contentFilters]);

  const mappedTypes = useMemo(() => types.map(t => {
    const upper = t.toUpperCase();
    if (upper === 'QCM') return 'MULTIPLE_CHOICE';
    if (upper === 'QROC') return 'QROC';
    return 'SINGLE_CHOICE';
  }), [types]);

  // Validate if all required filters are present for practice sessions
  const areRequiredFiltersComplete = useMemo(() => {
    // For practice sessions, the minimum requirement is having courses selected
    const hasCourses = selectedCourseIdsNum.length > 0;

    // Additional validation: ensure we have a valid unit or module selection
    const hasValidSelection = (unitId && unitId !== "") || moduleIds.length > 0;

    console.log('🔍 [Practice Session Wizard] Filter validation:', {
      hasCourses,
      hasValidSelection,
      courseCount: selectedCourseIdsNum.length,
      unitId,
      moduleCount: moduleIds.length,
      isComplete: hasCourses && hasValidSelection
    });

    return hasCourses && hasValidSelection;
  }, [selectedCourseIdsNum, unitId, moduleIds]);

  const filtersForCounts = useMemo(() => ({
    courseIds: selectedCourseIdsNum,
    questionTypes: mappedTypes.length > 0 ? mappedTypes as Array<'SINGLE_CHOICE' | 'MULTIPLE_CHOICE' | 'QROC'> : undefined,
    years: quizYears.length > 0 ? quizYears : undefined,
    questionSourceIds: quizSourceIds.length > 0 ? quizSourceIds : undefined,
    universityIds: [1],
    rotations: [], // Always empty for practice sessions
    ...(repetitionOnly ? { repetitionCountMin: 1 } : {}),
  }), [selectedCourseIdsNum, mappedTypes, quizYears, quizSourceIds, repetitionOnly]);


  const debouncedFilters = useDebounce(filtersForCounts, 300);

  // Track last filters to prevent duplicate calls
  const lastFiltersRef = useRef<string>('');

  // Fetch question count only when all required filters are complete AND we're in Step 2 or later
  useEffect(() => {
    if (areRequiredFiltersComplete && step >= 2) {
      // Create a stable key for comparison
      const filtersKey = JSON.stringify(debouncedFilters);

      // Only fetch if filters have actually changed
      if (filtersKey !== lastFiltersRef.current) {
        console.log('🚀 [Practice Session Wizard] Fetching question count with complete filters:', debouncedFilters);
        lastFiltersRef.current = filtersKey;
        refetchQuestionCount(debouncedFilters);
      } else {
        console.log('⏸️ [Practice Session Wizard] Skipping question count fetch - filters unchanged');
      }
    } else {
      console.log('⏸️ [Practice Session Wizard] Skipping question count fetch - incomplete filters or not in Step 2+');
      // Reset the ref when conditions are not met
      lastFiltersRef.current = '';
    }
  }, [debouncedFilters, areRequiredFiltersComplete, step]);

  // Use the new question count from the API
  const totalAvailable = availableQuestionCount;

  // Provide a simple breakdown for UI display (since the new API doesn't provide type breakdown)
  const counts = useMemo(() => {
    if (!totalAvailable) return null;

    // Simple fallback - we don't have actual breakdown from the new API
    // This is just for UI display purposes
    return {
      MULTIPLE_CHOICE: totalAvailable, // Show total for now
      SINGLE_CHOICE: totalAvailable,   // Show total for now
    };
  }, [totalAvailable]);

  useEffect(() => {
    // Update questionCount when available total changes
    if (totalAvailable > 0) {
      // Only set question count if we don't have a previous value
      // Use a reasonable default based on available questions (no hardcoded fallbacks)
      setQuestionCount((prev) => {
        if (prev && prev > 0) {
          // Keep existing value but ensure it's within bounds
          return Math.min(prev, totalAvailable);
        } else {
          // Set initial value to a reasonable percentage of available questions
          const initialCount = Math.min(Math.max(Math.floor(totalAvailable * 0.1), 1), 20);
          return Math.min(initialCount, totalAvailable);
        }
      });
    } else {
      setQuestionCount(0);
    }
  }, [totalAvailable]);

  // Step 1 validation: requires title and unit/module selection
  const step1Valid = !!title && ((unitId && unitId !== "") || moduleIds.length > 0);
  const step2Valid = totalAvailable > 0 && questionCount > 0 && questionCount <= totalAvailable && !questionCountError;

  const canNext = useMemo(() => {
    if (step === 1) return step1Valid && !contentLoading && !contentError && !sessionFiltersLoading && !sessionFiltersError;
    if (step === 2) return step2Valid && !questionCountLoading && !sessionFiltersLoading && !sessionFiltersError;
    return true;
  }, [step, step1Valid, step2Valid, contentLoading, contentError, questionCountLoading, questionCountError, sessionFiltersLoading, sessionFiltersError, courseIds.length]);

  const handleCreate = () => {
    const finalTitle = (title.trim() || suggestedTitle || 'Practice Session').slice(0, 200);
    if (finalTitle.length < 3) return; // enforce min 3 chars

    // Extract course IDs based on current selections
    let finalCourseIds: number[] = [];

    // If specific courses are selected, use those
    if (courseIds.length > 0) {
      finalCourseIds = courseIds.map(Number);
    } else {
      // Otherwise, extract course IDs from unit/module selections
      finalCourseIds = extractCourseIdsFromContentFilters();
    }

    // Prepare filters for the new API format
    const sessionFilters = {
      questionTypes: types.map(t => {
        const upper = t.toUpperCase();
        if (upper === 'QCM') return 'MULTIPLE_CHOICE';
        if (upper === 'QROC') return 'QROC';
        return 'SINGLE_CHOICE';
      }) as Array<'SINGLE_CHOICE' | 'MULTIPLE_CHOICE' | 'QROC'>,
      questionSourceIds: quizSourceIds.length ? quizSourceIds : undefined,
      years: quizYears.length ? quizYears : undefined,
      universityIds: [1],
      rotations: [], // Always empty for practice sessions
      ...(repetitionOnly ? { repetitionCountMin: 1 } : {}),
    };


    onCreate({
      title: finalTitle,
      program: program.trim() || undefined,
      unitId: unitId && unitId !== "" ? Number(unitId) : undefined,
      // expose moduleIds for multi-select
      ...(moduleIds.length ? { moduleIds: moduleIds.map(Number) } : {} as any),
      courseIds: finalCourseIds, // Use extracted course IDs
      availableCount: totalAvailable,
      filters: {
        types,
        quizSourceIds,
        quizYears: quizYears.length ? quizYears : undefined,
        universityIds: [1],
        rotations: [], // Always empty for practice sessions
      },

      // New API format filters
      sessionFilters,
      questionCount: questionCount || undefined,
      timeLimit: timeLimit,
    } as any);
  };

  // Animation variants for step transitions
  const variants = {
    initial: (direction: number) => ({
      x: `${110 * direction}%`,
      opacity: 0,
    }),
    animate: { x: "0%", opacity: 1 },
    exit: (direction: number) => ({
      x: `${-110 * direction}%`,
      opacity: 0,
    }),
  };

  // Render step content based on current step
  const renderStepContent = () => {
    switch (step) {
      case 1:
        return (
          <div className="space-y-5">
            <div className="space-y-5">
              {/* Year Level Selection - Only show for SEVEN (Résidanat) students */}
              {shouldApplyFilter && (
                <YearLevelSelector
                  value={selectedYearLevel as any}
                  onChange={(yearLevel) => {
                    setSelectedYearLevel(yearLevel);
                    // Reset selections when year level changes
                    setUnitId("");
                    setModuleIds([]);
                    setCourseIds([]);
                  }}
                  loading={yearLevelLoading}
                  showAllOption={false}
                  placeholder={
                    yearLevelLoading
                      ? "Loading..."
                      : "Select year"
                  }
                  triggerClassName="shadow-none"
                />
              )}

              {/* Unit Selection */}
              <div className="space-y-2">
                <Label>Unit</Label>
                <UnitSelectSheet
                  value={unitId}
                  onChange={(v) => {
                    setUnitId(v);
                    setModuleIds([]);
                    setCourseIds([]);
                  }}
                  options={availableUnits}
                  placeholder={contentLoading ? "Loading units..." : "Select unit"}
                  loading={contentLoading}
                  error={contentError}
                  title="Select Unit"
                  description="Choose a unit for your practice session"
                  searchPlaceholder="Search units..."
                  className="shadow-none"
                />
              </div>

              {/* Modules Selection */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label>
                    Modules
                    {availableModules.length > 0 && (
                      <span className="text-xs text-muted-foreground ml-1">
                        ({moduleIds.length}/{availableModules.length})
                      </span>
                    )}
                  </Label>
                </div>
                <ModuleSelectSheet
                  options={availableModules}
                  value={moduleIds}
                  onChange={(vals) => { setModuleIds(vals); setCourseIds([]); }}
                  placeholder={!unitId || unitId === "" ? "Select unit first" : (contentLoading ? "Loading modules..." : "Select modules")}
                  title="Select Modules"
                  description={!unitId || unitId === "" ? "Please select a unit first" : "Choose modules to include in your practice session"}
                  searchPlaceholder="Search modules..."
                  emptySearchMessage="No modules found"
                  disabled={!unitId || unitId === "" || contentLoading}
                  loading={contentLoading}
                  showSelectAll={unitId && unitId !== "" && availableModules.length > 0}
                  className="shadow-none"
                />
              </div>

              {/* Courses Selection */}
              <div className="space-y-4">
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label>
                      Courses
                      {availableCourses.length > 0 && (
                        <span className="text-xs text-muted-foreground ml-1">
                          ({courseIds.length}/{availableCourses.length})
                        </span>
                      )}
                    </Label>
                  </div>
                  <CourseSelectSheet
                    options={availableCourses}
                    value={courseIds}
                    onChange={handleCourseSelection}
                    placeholder={
                      !unitId && !moduleIds.length
                        ? "Select unit or modules first"
                        : contentLoading
                          ? "Loading courses..."
                          : contentError
                            ? "Error loading courses"
                            : availableCourses.length === 0
                              ? "No courses available"
                              : "Select courses"
                    }
                    title="Select Courses"
                    description={
                      !unitId && !moduleIds.length
                        ? "Please select a unit or modules first"
                        : "Choose courses to include in your practice session"
                    }
                    searchPlaceholder="Search courses..."
                    emptySearchMessage="No courses found"
                    disabled={(!unitId && !moduleIds.length) || contentLoading}
                    loading={contentLoading}
                    error={contentError}
                    showSelectAll={(unitId || moduleIds.length > 0) && availableCourses.length > 0}
                    className="shadow-none"
                  />

                  {/* Course Loading/Error States */}
                  {contentError && (
                    <div className="text-sm text-red-600 mt-1">
                      Error loading courses: {contentError}
                    </div>
                  )}

                </div>
              </div>
            </div>
          </div>
        );
      case 2:
        return (
          <div className="space-y-5">

            {/* Session filters loading state */}
            {sessionFiltersLoading && (
              <div className="flex items-center gap-4 p-4 border rounded-lg bg-muted/20">
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-primary"></div>
                <div className="text-sm text-muted-foreground">
                  Loading filter options...
                </div>
              </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3" aria-live="polite">
              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <Label>
                    Question Types
                  </Label>
                </div>
                <SimpleMultiSelectDialog
                  options={[{ label: 'QCM', value: 'qcm' }, { label: 'QCS', value: 'qcs' }, { label: 'QROC', value: 'qroc' }]}
                  value={types}
                  onChange={setTypes}
                  placeholder="Select one or more types"
                  title="Select Question Types"
                  description="Choose the types of questions to include"
                  className="shadow-none"
                />
              </div>

              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <Label>
                    Exam Years
                    {availableYearOptions.length > 0 && (
                      <span className="text-xs text-muted-foreground ml-1">
                        ({quizYears.length}/{availableYearOptions.length})
                      </span>
                    )}
                  </Label>
                </div>
                <MultiSelectSheet
                  options={(sessionFilters?.examYears || []).map((y: any) => {
                    const year = typeof y === 'object' ? y.year : y;
                    return { label: String(year), value: String(year) };
                  })}
                  value={quizYears.map(String)}
                  onChange={(vals) => setQuizYears(vals.map((v) => Number(v)))}
                  placeholder={sessionFiltersLoading ? "Loading years..." : sessionFiltersError ? "Error loading years" : "Select years (optional)"}
                  title="Select Exam Years"
                  description="Choose exam years to include (optional)"
                  disabled={sessionFiltersLoading || !!sessionFiltersError}
                  loading={sessionFiltersLoading}
                  error={sessionFiltersError}
                  searchPlaceholder="Search years..."
                  emptySearchMessage="No years found"
                  className="shadow-none"
                />
              </div>

              <div className="space-y-1.5">
                <div className="flex items-center justify-between">
                  <Label>
                    Sources
                  </Label>
                </div>
                <MultiSelectSheet
                  options={(sessionFilters?.questionSources || []).map((s: any) => ({ value: String(s.id), label: s.name }))}
                  value={quizSourceIds.map(String)}
                  onChange={(vals) => setQuizSourceIds(vals.map((v) => Number(v)))}
                  placeholder={sessionFiltersLoading ? "Loading sources..." : sessionFiltersError ? "Error loading sources" : "Select sources (optional)"}
                  title="Select Sources"
                  description="Choose question sources to include (optional)"
                  searchPlaceholder="Search sources..."
                  emptySearchMessage="No sources found"
                  disabled={sessionFiltersLoading || !!sessionFiltersError}
                  loading={sessionFiltersLoading}
                  error={sessionFiltersError}
                  className="shadow-none"
                />
              </div>

              {/* Repetition filter switch */}
              <div className="col-span-1 md:col-span-2 flex items-center space-x-3 pt-1">
                <Switch
                  id="repetition-only"
                  checked={repetitionOnly}
                  onCheckedChange={(checked) => setRepetitionOnly(checked === true)}
                  className="h-6 w-11 data-[state=checked]:bg-primary"
                />
                <label
                  htmlFor="repetition-only"
                  className="text-sm font-bold leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70 cursor-pointer select-none"
                >
                  Practice only repeated questions
                </label>
              </div>

            </div>

            {/* Keep years and sources consistent: prune selected years if not allowed by selected sources */}
            {(() => {
              const selectedSourceYears = new Set<number>();
              (sessionFilters?.questionSources || [])
                .filter((s: any) => quizSourceIds.includes(Number(s.id)))
                .forEach((s: any) => (s.availableYears || []).forEach((y: number) => selectedSourceYears.add(y)));
              // Union of allowed by selected sources; if none selected, allow all questionYears
              const allYears = (sessionFilters?.examYears || []).map((y: any) => typeof y === 'object' ? y.year : y);
              const allowedYears = selectedSourceYears.size ? Array.from(selectedSourceYears) : allYears;
              if (quizYears.length && allowedYears.length) {
                const pruned = quizYears.filter((y) => allowedYears.includes(y));
                if (pruned.length !== quizYears.length) setQuizYears(pruned);
              }
              return null;
            })()}

            {/* Question count with -/+ buttons */}
            <div className="space-y-1.5">
              <Label>Question Count</Label>
              <div className="flex items-center gap-3">
                <div className="flex-1">
                  <Slider
                    min={1}
                    max={Math.max(1, totalAvailable)}
                    value={[Math.min(Math.max(1, questionCount), Math.max(1, totalAvailable))]}
                    onValueChange={([v]) => setQuestionCount(v)}
                    disabled={questionCountLoading || totalAvailable === 0 || !!questionCountError}
                    aria-valuetext={`${questionCount} questions`}
                  />
                </div>
                <div className="flex items-center">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="rounded-r-none h-9"
                    onClick={() => setQuestionCount(prev => Math.max(1, prev - 1))}
                    disabled={questionCountLoading || questionCount <= 1 || totalAvailable === 0 || !!questionCountError}
                  >
                    -
                  </Button>
                  <input
                    type="number"
                    min={1}
                    max={Math.max(1, totalAvailable)}
                    value={questionCountLoading ? '' : questionCountError ? '' : questionCount}
                    onChange={(e) => {
                      const value = parseInt(e.target.value) || 1;
                      const clampedValue = Math.min(Math.max(1, value), Math.max(1, totalAvailable));
                      setQuestionCount(clampedValue);
                    }}
                    disabled={questionCountLoading || totalAvailable === 0 || !!questionCountError}
                    placeholder={questionCountLoading ? '...' : questionCountError ? '—' : '1'}
                    className="w-14 text-center text-sm border border-input bg-background px-2 py-1 h-9 focus:outline-none focus:ring-2 focus:ring-ring focus:border-transparent disabled:opacity-50 disabled:cursor-not-allowed sm:w-16 md:w-18 lg:w-20"
                    aria-label="Question count"
                  />
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    className="rounded-l-none h-9"
                    onClick={() => setQuestionCount(prev => Math.min(totalAvailable, prev + 1))}
                    disabled={questionCountLoading || questionCount >= totalAvailable || totalAvailable === 0 || !!questionCountError}
                  >
                    +
                  </Button>
                </div>
              </div>
              <p className="text-xs text-muted-foreground">
                Max available: {questionCountLoading ? '...' : questionCountError ? 'Unavailable' : totalAvailable}
              </p>
            </div>


          </div>
        );
      default:
        return null;
    }
  };

  return (
    <div className="space-y-6">
      {/* Error handling */}
      {contentError && (
        <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4">
          <p className="text-sm text-destructive">
            Failed to load content: {contentError}
          </p>
        </div>
      )}

      {/* Session filters error handling */}
      {sessionFiltersError && (
        <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-destructive font-medium">Failed to load session filters</p>
              <p className="text-xs text-destructive/80 mt-1">{sessionFiltersError}</p>
            </div>
            <Button
              onClick={refetchSessionFilters}
              variant="outline"
              size="sm"
              disabled={sessionFiltersLoading}
              className="text-destructive border-destructive/20 hover:bg-destructive/10"
            >
              <RefreshCw className={`h-4 w-4 mr-2 ${sessionFiltersLoading ? 'animate-spin' : ''}`} />
              Retry
            </Button>
          </div>
        </div>
      )}

      {/* Header with title and stepper - matching multi-step-form.tsx style */}
      <div className="flex flex-row items-start justify-between space-y-0 px-6 py-4">
        <div className="flex flex-col gap-1">
          <h2 className="text-xl font-semibold">Create Serie</h2>
          <p className="text-sm text-muted-foreground">
            {step === 1 && "Select units, modules, and courses for your practice serie."}
            {step === 2 && "Configure question filters and Review serie settings."}
          </p>
        </div>
        <div className="flex items-center gap-1.5 pt-1">
          {[1, 2].map((i) => (
            <div
              key={i}
              className={cn(
                "h-2 rounded-full transition-all duration-300",
                step === i
                  ? "w-8 bg-primary"
                  : "w-2 bg-primary/20"
              )}
            />
          ))}
        </div>
      </div>

      {/* Animated Step Content */}
      <MotionConfig
        transition={{
          duration: 0.5,
          type: "spring",
          bounce: 0,
        }}
      >
        <motion.div
          animate={{ height: bounds.height > 0 ? bounds.height : "auto" }}
          className="relative overflow-hidden"
          transition={{ type: "spring", bounce: 0, duration: 0.5 }}
        >
          <div ref={contentRef}>
            <AnimatePresence
              mode="popLayout"
              initial={false}
              custom={direction}
            >
              <motion.div
                key={step}
                variants={variants}
                initial="initial"
                animate="animate"
                exit="exit"
                className="w-full"
                custom={direction}
              >
                {renderStepContent()}
              </motion.div>
            </AnimatePresence>
          </div>
        </motion.div>
      </MotionConfig>

      {/* Footer actions */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 pt-4 border-t border-border/50">
        <Button variant="outline" onClick={clearAllSelections} className="text-muted-foreground hover:text-foreground w-full sm:w-auto">
          <X className="w-4 h-4 mr-2" />
          Clear All
        </Button>
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2 w-full sm:w-auto">
          {step > 1 && (
            <Button variant="secondary" onClick={prev} className="w-full sm:w-auto">
              <ChevronLeft className="w-4 h-4 mr-1" /> Previous
            </Button>
          )}
          {step < 2 ? (
            <Button onClick={next} disabled={!canNext} className="w-full sm:w-auto">
              Next <ChevronRight className="w-4 h-4 ml-1" />
            </Button>
          ) : (
            <Button
              onClick={handleCreate}
              disabled={isCreating || !(step1Valid && step2Valid) || totalAvailable === 0 || questionCountLoading || !!questionCountError || sessionFiltersLoading || !!sessionFiltersError}
              className="practice-button w-full sm:w-auto"
              aria-disabled={isCreating || !(step1Valid && step2Valid) || totalAvailable === 0 || questionCountLoading || !!questionCountError || sessionFiltersLoading || !!sessionFiltersError}
            >
              {isCreating ? (
                <>
                  <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                  Creating...
                </>
              ) : (
                'Create Serie'
              )}
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}

